/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.EmpClass;
import com.sun.javafx.tk.Toolkit;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author LENOVO
 */
public class addemployee extends javax.swing.JFrame {

    /**
     * Creates new form addemployee
     */
    EmpClass emp=new EmpClass();
    public addemployee() {
        initComponents();
          setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namemep2 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        surname = new javax.swing.JLabel();
        namemep1 = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        cnic = new javax.swing.JLabel();
        phone3 = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        email2 = new javax.swing.JLabel();
        snametxt = new javax.swing.JTextField();
        phnotxt = new javax.swing.JTextField();
        addres = new javax.swing.JTextField();
        cnicno = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        surname1 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        pswdEmp = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Image = new javax.swing.JLabel();
        Photo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        namemep2.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        namemep2.setText("Name: ");

        phone1.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        phone1.setText("Phone:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        submit.setText("Submit");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 730, -1, -1));

        surname.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        surname.setText("Surname: ");
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, 41));

        namemep1.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        namemep1.setText("Name: ");
        getContentPane().add(namemep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 180, 41));

        address.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        address.setText("Address:");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 150, 41));

        cnic.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        cnic.setText("CNIC No:");
        getContentPane().add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 252, 41));

        phone3.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        phone3.setText("Phone:");
        getContentPane().add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 41));

        pass.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        pass.setText("Password:");
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 252, 41));

        email1.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        email1.setText("Confirm Password:");
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 320, 41));

        email2.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        email2.setText("Email:");
        getContentPane().add(email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 130, 41));

        snametxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        snametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snametxtActionPerformed(evt);
            }
        });
        getContentPane().add(snametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 241, 39));

        phnotxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        phnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnotxtActionPerformed(evt);
            }
        });
        getContentPane().add(phnotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 252, 39));

        addres.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresActionPerformed(evt);
            }
        });
        getContentPane().add(addres, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 416, 39));

        cnicno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cnicno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicnoActionPerformed(evt);
            }
        });
        getContentPane().add(cnicno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 252, 39));

        nametxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });
        getContentPane().add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 252, 39));

        email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 416, 39));

        surname1.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        surname1.setText("Add Employee");
        getContentPane().add(surname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 340, 41));

        submit1.setBackground(new java.awt.Color(255, 255, 255));
        submit1.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        submit1.setText("Cancel");
        submit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        getContentPane().add(submit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 720, -1, -1));
        getContentPane().add(pswdEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 250, 40));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 620, 250, 40));

        Image.setBackground(new java.awt.Color(255, 255, 255));
        Image.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        Image.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Image.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Downloads\\dp.jpg")); // NOI18N
        Image.setLabelFor(Photo);
        Image.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Image.setMaximumSize(new java.awt.Dimension(208, 212));
        Image.setMinimumSize(new java.awt.Dimension(208, 212));
        Image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImageMouseClicked(evt);
            }
        });
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 180, 190));

        Photo.setBackground(new java.awt.Color(255, 255, 255));
        Photo.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        Photo.setText("Upload a Photo");
        Photo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotoActionPerformed(evt);
            }
        });
        getContentPane().add(Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void snametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snametxtActionPerformed

    private void phnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnotxtActionPerformed

    private void addresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresActionPerformed

    private void cnicnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicnoActionPerformed

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
             String pass = String.valueOf(pswdEmp.getPassword());
         if(nametxt.getText().isEmpty()||snametxt.getText().isEmpty()||email.getText().isEmpty()||phnotxt.getText().isEmpty()||addres.getText().isEmpty()|| pass.isEmpty()|| cnicno.getText().isEmpty()||photo.toString().isEmpty())
         {
              JOptionPane.showMessageDialog(null,"Please fill all column");
         }
         else{
        emp.addEmp(nametxt.getText(),snametxt.getText(),email.getText(),phnotxt.getText(),addres.getText(), pass,cnicno.getText(),photo.toString());
             dispose();
        new     employeeform().setVisible(true);
        this.setVisible(false);
                }
                
    }//GEN-LAST:event_submitActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
         dispose();
        new employeeform().setVisible(true);
    }//GEN-LAST:event_submit1ActionPerformed

    private void ImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageMouseClicked

    private void PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotoActionPerformed
JFileChooser chooser= new  JFileChooser();  
chooser.showOpenDialog(null);
File  f = chooser.getSelectedFile();
Image.setIcon(new ImageIcon(f.toString()));
filename =f.getAbsolutePath();

try{
File  image = new File(filename);
FileInputStream fis= new FileInputStream(image);
ByteArrayOutputStream bos = new ByteArrayOutputStream();
 byte[] buf = new byte[1024];
    for (int readNum ; (readNum = fis.read(buf))!=-1;) {
        bos.write(buf, 0, readNum);
        
    }
photo= bos.toByteArray();
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}


// TODO add your handling code here:
    }//GEN-LAST:event_PhotoActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Image;
    private javax.swing.JButton Photo;
    private javax.swing.JTextField addres;
    private javax.swing.JLabel address;
    private javax.swing.JLabel cnic;
    private javax.swing.JTextField cnicno;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel email2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel namemep1;
    private javax.swing.JLabel namemep2;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField phnotxt;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone3;
    private javax.swing.JPasswordField pswdEmp;
    private javax.swing.JTextField snametxt;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JLabel surname;
    private javax.swing.JLabel surname1;
    // End of variables declaration//GEN-END:variables
byte[] photo = null;
String filename= null;
}
