package project;


import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Salas Ali
 */
public class Admin_Log extends javax.swing.JFrame {

    /**
     * Creates new form LoginUser
     */
    //UserLogin_Class u_login = new UserLogin_Class();

    public Admin_Log() {
        initComponents();
          setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtuname1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        p_upass1 = new javax.swing.JPasswordField();
        backB = new javax.swing.JButton();
        btnlogin1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ADMIN ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, 54));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setText("Username: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 200, 47));

        txtuname1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtuname1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtuname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuname1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtuname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 370, 60));

        jLabel9.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel9.setText("Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        p_upass1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        p_upass1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        p_upass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_upass1ActionPerformed(evt);
            }
        });
        getContentPane().add(p_upass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 370, 60));

        backB.setBackground(new java.awt.Color(255, 255, 255));
        backB.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        backB.setText("Cancel");
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, 102, 44));

        btnlogin1.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin1.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        btnlogin1.setText("Login");
        btnlogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 710, 99, 44));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // TODO add your handling code here:
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_backBActionPerformed

    private void p_upass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_upass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_upass1ActionPerformed

    private void btnlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogin1ActionPerformed
        // TODO add your handling code here:
        String uname = txtuname1.getText();
        String pass = String.valueOf(p_upass1.getPassword());
        String u="Admin";
        String p="Admin123";

        if(uname.compareTo(u)==0  && pass.compareTo(p)==0)
        {
            JOptionPane.showMessageDialog(null,"Admin Logged In");
            dispose();
            new Dashboard().setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid");
        }
        //   String pass = String.valueOf(p_upass1.getPassword());
        //   u_login.LoginUser(txtuname.getText(), pass);
        // Dashboard db = new Dashboard();
        // db.setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_btnlogin1ActionPerformed

    private void txtuname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuname1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JButton btnlogin1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField p_upass1;
    private javax.swing.JTextField txtuname1;
    // End of variables declaration//GEN-END:variables
}
