/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.EmpClass;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class deletemp extends javax.swing.JFrame {

    EmpClass emp=new EmpClass();
    /**
     * Creates new form deletemp
     */
    public deletemp() {
        initComponents();
       setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteemo = new javax.swing.JLabel();
        empcnic = new javax.swing.JTextField();
        surname = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        empEmail = new javax.swing.JTextField();
        del = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteemo.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        deleteemo.setText("Delete Employee");
        getContentPane().add(deleteemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 370, 41));

        empcnic.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        empcnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empcnicActionPerformed(evt);
            }
        });
        getContentPane().add(empcnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 470, 60));

        surname.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        surname.setText("Employee CNIC:");
        getContentPane().add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 280, 41));

        id.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        id.setText("Employee Email:");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 290, 41));

        empEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        empEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEmailActionPerformed(evt);
            }
        });
        getContentPane().add(empEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 470, 60));

        del.setBackground(new java.awt.Color(255, 255, 255));
        del.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        del.setText("Delete");
        del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 640, -1, -1));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        back.setText("Cancel");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empcnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empcnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empcnicActionPerformed

    private void empEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empEmailActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         dispose();
        new employeeform().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
          int dialogRes =JOptionPane.showConfirmDialog(null, "Do you want to delete Record?", "Warning", JOptionPane.YES_NO_OPTION);
     
        if(dialogRes== JOptionPane.YES_NO_OPTION)
        {
           
             emp.deleteEmployee(empEmail.getText(),empcnic.getText());
        dispose();
        new employeeform().setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_delActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton del;
    private javax.swing.JLabel deleteemo;
    private javax.swing.JTextField empEmail;
    private javax.swing.JTextField empcnic;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel surname;
    // End of variables declaration//GEN-END:variables
}
