/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.EmpClass;

/**
 *
 * @author LENOVO
 */
public class empupdatepass extends javax.swing.JFrame {
EmpClass empAd=new EmpClass();
    /**
     * Creates new form empupdatepass
     */
    public empupdatepass() {
        initComponents();
          setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmpass = new javax.swing.JLabel();
        bckbtn = new javax.swing.JButton();
        updtBtn = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        newpass = new javax.swing.JLabel();
        update = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmpass.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        confirmpass.setText("New Password:");
        getContentPane().add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 250, 41));

        bckbtn.setBackground(new java.awt.Color(255, 255, 255));
        bckbtn.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        bckbtn.setText("Cancel");
        bckbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bckbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        updtBtn.setBackground(new java.awt.Color(255, 255, 255));
        updtBtn.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        updtBtn.setText("Update");
        updtBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 130, -1));

        email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 450, 50));

        newpass.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        newpass.setText("Email: ");
        getContentPane().add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 120, 41));

        update.setFont(new java.awt.Font("Footlight MT Light", 3, 48)); // NOI18N
        update.setText("Update Password");
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 400, -1));

        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });
        getContentPane().add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 450, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void updtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtBtnActionPerformed
        // TODO add your handling code here:
        String newpswd = String.valueOf(newPass.getPassword());
        empAd.updatePass(email.getText(),newpswd);
        dispose();
        new employeeform().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updtBtnActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new employeeform().setVisible(true);
    }//GEN-LAST:event_bckbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empupdatepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empupdatepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empupdatepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empupdatepass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empupdatepass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bckbtn;
    private javax.swing.JLabel confirmpass;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JLabel newpass;
    private javax.swing.JLabel update;
    private javax.swing.JButton updtBtn;
    // End of variables declaration//GEN-END:variables
}
