/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.DbConnection;
import Classes.statistics;
import Classes.statistics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import project.Statistics;
import project.Statistics;

/**
 *
 * @author LENOVO
 */
public class Issuebooks extends javax.swing.JFrame {
 SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
   
 Statement stmt = null;
  PreparedStatement pst = null;
    ResultSet rs = null;
    DbConnection db_con = new DbConnection();
    Connection conn = db_con.GenerateConnection(); /**
     * Creates new form Issuebooks
     */
    public Issuebooks() {
        initComponents();
         setLocation(400,100);
        setSize(1199, 868);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        typeTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bname = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        issue = new com.toedter.calendar.JDateChooser();
        returns = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        atxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        typeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTxtActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel1.setText("Issue Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 243, 82));

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel2.setText("Book Name: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel3.setText("Student Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 260, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel4.setText("Issue Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 180, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel5.setText("Return Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, 220, -1));

        bname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 320, 60));

        sname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 470, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton1.setText("Issue");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 720, 139, 54));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 720, 127, 54));

        issue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 210, 40));

        returns.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(returns, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 210, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton3.setText("search");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 105, 44));

        jLabel6.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel6.setText("Author  Name: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        atxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(atxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 320, 60));

        jLabel7.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 121, 32));

        idTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 320, 60));

        type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 320, 60));

        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Book Id:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 160, 32));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(bname.getText().isEmpty()|| sname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please fill all column");
        }
        else
        {   String idate=sdf.format(issue.getDate()); 
        String rdate=sdf.format(returns.getDate());
           statistics st=new  statistics(bname.getText(),sname.getText(),idate,rdate,idTxt.getText(),atxt.getText(),type.getText());
       st.issuedbooks(); }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Statistics().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String bookName=bname.getText();
        //String stemail=sname.getText();
        // boolean b=st.search(bookName,stemail);();

        try{
            String query="(select * from booklist where ID='"+idTxt.getText()+"' )" ;
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            if (rs.next()) {
                // JOptionPane.showMessageDialog(null, "");
                bname.setText(rs.getString(1));
                atxt.setText(rs.getString(2));
                type.setText(rs.getString(3));
                bname.setEditable(false);
               idTxt.setEditable(false);
               
            } else {
                JOptionPane.showMessageDialog(null,"book is not available");

            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void typeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTxtActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issuebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atxt;
    private javax.swing.JTextField bname;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JTextField idTxt;
    private com.toedter.calendar.JDateChooser issue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser returns;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField type;
    private javax.swing.JTextField typeTxt;
    // End of variables declaration//GEN-END:variables
}
