package project;

import Classes.SignupUser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author LENOVO
 */
public class Login_Stu extends javax.swing.JFrame {
  SignupUser log=new SignupUser();
  // String stand=stuname.getText();
  // StuDash logstu =new StuDas       
    /**
     * Creates new form Login_Stu
     */
  
    public Login_Stu() {
        initComponents();
         setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignStu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stuname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stupswd = new javax.swing.JPasswordField();
        backB = new javax.swing.JButton();
        stuLoginbtn = new javax.swing.JButton();
        updtbtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignStu.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        SignStu.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\sinup-removebg-preview.png")); // NOI18N
        SignStu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignStu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignStuMouseClicked(evt);
            }
        });
        jPanel1.add(SignStu, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 160, 100));

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel2.setText("Student Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 330, 54));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 123, 47));

        stuname.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        stuname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        stuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunameActionPerformed(evt);
            }
        });
        jPanel1.add(stuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 430, 60));

        jLabel9.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 180, -1));

        stupswd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        stupswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        stupswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stupswdActionPerformed(evt);
            }
        });
        jPanel1.add(stupswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 430, 60));

        backB.setBackground(new java.awt.Color(255, 255, 255));
        backB.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        backB.setText("Cancel");
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        jPanel1.add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 102, 44));

        stuLoginbtn.setBackground(new java.awt.Color(255, 255, 255));
        stuLoginbtn.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        stuLoginbtn.setText("Login");
        stuLoginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stuLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuLoginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(stuLoginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 680, 101, 44));

        updtbtn.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        updtbtn.setText("Update Password");
        updtbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updtbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updtbtnMouseClicked(evt);
            }
        });
        jPanel1.add(updtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 200, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameActionPerformed

    private void stupswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stupswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stupswdActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
      dispose();
    new Main().setVisible(true);
    }//GEN-LAST:event_backBActionPerformed

    private void stuLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuLoginbtnActionPerformed
        // TODO add your handling code here:
        String pass = String.valueOf(stupswd.getPassword());
       
       boolean b= log.loginStu(stuname.getText(), pass);
       if(b== true)
       {
        dispose();
        new StuDash().setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_stuLoginbtnActionPerformed

    private void SignStuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignStuMouseClicked
        // TODO add your handling code here:
        dispose();
    new UserSignUp().setVisible(true);
    }//GEN-LAST:event_SignStuMouseClicked

    private void updtbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updtbtnMouseClicked
        // TODO add your handling code here:
          Update_Pswd p_upadte = new Update_Pswd();
       p_upadte.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_updtbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Stu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Stu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Stu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Stu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Stu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignStu;
    private javax.swing.JButton backB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stuLoginbtn;
    private javax.swing.JTextField stuname;
    private javax.swing.JPasswordField stupswd;
    private javax.swing.JLabel updtbtn;
    // End of variables declaration//GEN-END:variables
}
