/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import Classes.Books;
import Classes.DbConnection;
import Classes.statistics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ReturnBook extends javax.swing.JFrame {
    int fine=0;
    SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
statistics st=new statistics();
 Statement stmt = null;
  PreparedStatement pst = null;
    ResultSet rs = null;
    DbConnection db_con = new DbConnection();
    Connection conn = db_con.GenerateConnection();
    boolean b,a = false;
    /** Creates new form ReturnBook */
    public ReturnBook() {
        super("Return Book");
        initComponents();
         setLocation(400,100);
        setSize(1199, 868);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        idate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rdate1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        atxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        returnDt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        rdate2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel1.setText("Return Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 349, 107));

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel2.setText("Book Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 210, 35));

        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel3.setText("Student Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 240, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel4.setText("Issue Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 190, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel5.setText("Return Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 210, 50));

        jLabel6.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel6.setText("Returning Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 270, -1));

        sname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 400, 50));

        bname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnameActionPerformed(evt);
            }
        });
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 270, 50));

        idate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idateActionPerformed(evt);
            }
        });
        getContentPane().add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 270, 50));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 105, 44));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton2.setText("Return");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, -1, -1));

        rdate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 270, 50));

        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setText("Author  Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 240, -1));

        atxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        atxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atxtActionPerformed(evt);
            }
        });
        getContentPane().add(atxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 270, 50));

        jLabel9.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Type:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 121, 60));

        idTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 270, 50));

        type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 340, 270, 50));

        jLabel10.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Book Id:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 170, 32));

        returnDt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        returnDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnDtActionPerformed(evt);
            }
        });
        getContentPane().add(returnDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 270, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, 90, 40));

        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, -1, -1));

        rdate2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdate2ActionPerformed(evt);
            }
        });
        getContentPane().add(rdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 270, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String bookName=bname.getText();     
        String stemail=sname.getText();
       // boolean b=st.search(bookName,stemail);();

        try{
           String query="(select * from isBook where stemail='"+stemail+"' and bkname='"+bookName+"')" ;
            pst = conn.prepareStatement(query);
            rs = pst.executeQuery();
            if (rs.next()) {
               // JOptionPane.showMessageDialog(null, "");
               idTxt.setText(rs.getString(5));
               atxt.setText(rs.getString(6));
               type.setText(rs.getString(7));
                idate.setText(rs.getString(3));
                 rdate1.setText(rs.getString(4));
                 bname.setEditable(false);
                 sname.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null,"student do not have this book!");
                
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"student do not have this book!");
           
        }
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    
        try{
            Date date1=sdf.parse(returnDt.getText());
            Date date2=sdf.parse(rdate1.getText());
            if(date1.after(date2))
            {
               // JOptionPane.showMessageDialog(null,"fine charged!");
                fine=100;
            }
            
        }
        catch(Exception ex)
                {
                    JOptionPane.showMessageDialog(null,ex);
                }
        
        st.updtReturn(sname.getText(), bname.getText(), returnDt.getText(),fine);
        st.deltFroIssue(sname.getText(), bname.getText());
        Books obj=new Books(idTxt.getText(), bname.getText(), atxt.getText(), type.getText());
        obj.addBook();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void atxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atxtActionPerformed

    private void rdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdate1ActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void rdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdate2ActionPerformed

    private void returnDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnDtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnDtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atxt;
    private javax.swing.JTextField bname;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField idate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField rdate1;
    private javax.swing.JTextField rdate2;
    private javax.swing.JTextField returnDt;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables

}
