/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.Employee;


/**
 *
 * @author LENOVO
 */
public class staff_update_pass extends javax.swing.JFrame {
 Employee log=new Employee();
    /**
     * Creates new form staff_update_pass
     */
    public staff_update_pass() {
        initComponents();
        setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        staff_email = new javax.swing.JTextField();
        oldpswd = new javax.swing.JPasswordField();
        newpswd = new javax.swing.JPasswordField();
        cancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel1.setText("Update Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 420, 90));

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 130, 80));

        jLabel3.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel3.setText("Old Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 250, 70));

        jLabel5.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel5.setText(" New Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 260, -1));

        staff_email.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        staff_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_emailActionPerformed(evt);
            }
        });
        getContentPane().add(staff_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 450, 50));

        oldpswd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        oldpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpswdActionPerformed(evt);
            }
        });
        getContentPane().add(oldpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 330, 50));

        newpswd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(newpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 330, 50));

        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        jButton1.setText("Update");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 700, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staff_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_emailActionPerformed

    private void oldpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpswdActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       dispose();
        new Staff_Log().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
           // TODO add your handling code here:
           String oldpass = String.valueOf(oldpswd.getPassword());
        String newpass = String.valueOf(newpswd.getPassword());
        log.updatePass(staff_email.getText(), oldpass,newpass);
        dispose();
        new Staff_Log().setVisible(true);
        this.setVisible(false);     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_update_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_update_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_update_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_update_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_update_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newpswd;
    private javax.swing.JPasswordField oldpswd;
    private javax.swing.JTextField staff_email;
    // End of variables declaration//GEN-END:variables
}
