/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.Employee;

/**
 *
 * @author LENOVO
 */
public class Staff_Log extends javax.swing.JFrame {
Employee emp=new Employee();
    /**
     * Creates new form Staff_Log
     */
    public Staff_Log() {
        initComponents();
            setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stuname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        stupswd = new javax.swing.JPasswordField();
        updtbtn = new javax.swing.JLabel();
        backB = new javax.swing.JButton();
        stuLoginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel2.setText("Staff Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 250, 54));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 123, 47));

        stuname.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        stuname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        stuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunameActionPerformed(evt);
            }
        });
        getContentPane().add(stuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 414, 47));

        jLabel9.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel9.setText("Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 170, -1));

        stupswd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        stupswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        stupswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stupswdActionPerformed(evt);
            }
        });
        getContentPane().add(stupswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 414, 46));

        updtbtn.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        updtbtn.setForeground(new java.awt.Color(51, 51, 51));
        updtbtn.setText("Update Password");
        updtbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updtbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updtbtnMouseClicked(evt);
            }
        });
        getContentPane().add(updtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 190, 28));

        backB.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        backB.setText("Cancel");
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 102, 44));

        stuLoginbtn.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        stuLoginbtn.setText("Login");
        stuLoginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stuLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuLoginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(stuLoginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 101, 44));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameActionPerformed

    private void stupswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stupswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stupswdActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_backBActionPerformed

    private void stuLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuLoginbtnActionPerformed
        // TODO add your handling code here:
        String pass = String.valueOf(stupswd.getPassword());

        boolean b= emp.loginEmp(stuname.getText(), pass);
        if(b== true)
        {
            dispose();
            new StaffDash().setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_stuLoginbtnActionPerformed

    private void updtbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updtbtnMouseClicked
        // TODO add your handling code here:
        staff_update_pass p_upadte = new staff_update_pass();
        p_upadte.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updtbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton stuLoginbtn;
    private javax.swing.JTextField stuname;
    private javax.swing.JPasswordField stupswd;
    private javax.swing.JLabel updtbtn;
    // End of variables declaration//GEN-END:variables
}
