/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.SignupUser;

/**
 *
 * @author LENOVO
 */
public class Update_Pswd extends javax.swing.JFrame {
 SignupUser log=new SignupUser();
    /**
     * Creates new form Update_Pswd
     */
    public Update_Pswd() {
        initComponents();
      setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        stuname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        oldPswd = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        newpswd = new javax.swing.JPasswordField();
        backB = new javax.swing.JButton();
        updtbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel2.setText("Update Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 400, 54));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 123, 47));

        stuname.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        stuname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        stuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunameActionPerformed(evt);
            }
        });
        getContentPane().add(stuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 450, 70));

        jLabel9.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel9.setText("Old Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 240, -1));

        oldPswd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        oldPswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        oldPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPswdActionPerformed(evt);
            }
        });
        getContentPane().add(oldPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 450, 70));

        jLabel10.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel10.setText("New Password:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 250, -1));

        newpswd.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        newpswd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        newpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpswdActionPerformed(evt);
            }
        });
        getContentPane().add(newpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 450, 70));

        backB.setBackground(new java.awt.Color(255, 255, 255));
        backB.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        backB.setText("Cancel");
        backB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, 102, 44));

        updtbtn.setBackground(new java.awt.Color(255, 255, 255));
        updtbtn.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        updtbtn.setText("Update");
        updtbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 680, 101, 44));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameActionPerformed

    private void oldPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPswdActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        dispose();
        new Login_Stu().setVisible(true);
    }//GEN-LAST:event_backBActionPerformed

    private void updtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtbtnActionPerformed
        // TODO add your handling code here:
       String oldpass = String.valueOf(oldPswd.getPassword());
        String newpass = String.valueOf(newpswd.getPassword());
        log.updatepass(stuname.getText(), oldpass,newpass);
        dispose();
        new Login_Stu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updtbtnActionPerformed

    private void newpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpswdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Pswd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Pswd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField newpswd;
    private javax.swing.JPasswordField oldPswd;
    private javax.swing.JTextField stuname;
    private javax.swing.JButton updtbtn;
    // End of variables declaration//GEN-END:variables
}
