/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import Classes.SignupUser;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class UserSignUp extends javax.swing.JFrame {
SignupUser u_signup = new SignupUser();
 SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");  /**
     * Creates new form UserSignUp
     */
    public UserSignUp() {
        initComponents();
       setLocation(400,100);
        setSize(1199, 868);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backB1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        eMail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        issue = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        pNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pswdS = new javax.swing.JPasswordField();
        backB2 = new javax.swing.JButton();
        signbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        backB1.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        backB1.setText("Back");
        backB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backB1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        jLabel2.setText("Create An Account ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 54));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel8.setText("First Name: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 47));

        fName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        getContentPane().add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 260, 47));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel11.setText("Gender:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 150, 47));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jRadioButton2.setText("Male");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 96, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        jRadioButton1.setText("Female");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 100, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel14.setText("Email:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 123, 47));

        eMail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        eMail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        eMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMailActionPerformed(evt);
            }
        });
        getContentPane().add(eMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 400, 47));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel10.setText("Last Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 200, 47));

        lName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });
        getContentPane().add(lName, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 260, 47));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel13.setText("Date of Birth:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 240, 47));
        getContentPane().add(issue, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 260, 33));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel12.setText("Phone no:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 170, 47));

        pNo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pNo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pNoActionPerformed(evt);
            }
        });
        getContentPane().add(pNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 266, 47));

        jLabel9.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel9.setText("Password:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 190, -1));

        pswdS.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pswdS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pswdS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdSActionPerformed(evt);
            }
        });
        getContentPane().add(pswdS, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 270, 46));

        backB2.setBackground(new java.awt.Color(255, 255, 255));
        backB2.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        backB2.setText("Cancel");
        backB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backB2ActionPerformed(evt);
            }
        });
        getContentPane().add(backB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 102, 44));

        signbtn.setBackground(new java.awt.Color(255, 255, 255));
        signbtn.setFont(new java.awt.Font("Bell MT", 3, 18)); // NOI18N
        signbtn.setText("Signup");
        signbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signbtnActionPerformed(evt);
            }
        });
        getContentPane().add(signbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 660, -1, 42));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\Zoom\\confirm.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void pswdSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdSActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void pNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pNoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void eMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMailActionPerformed

    private void backB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backB1ActionPerformed
        // TODO add your handling code here:
        Main b1=new Main();
        b1.setVisible(true);
    }//GEN-LAST:event_backB1ActionPerformed

    private void backB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backB2ActionPerformed
        // TODO add your handling code here:
        Login_Stu b1=new Login_Stu();
        b1.setVisible(true);
    }//GEN-LAST:event_backB2ActionPerformed

    private void signbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signbtnActionPerformed
        
       
            
        String idate=sdf.format(issue.getDate()); 
         String pass = String.valueOf(pswdS.getPassword());
         if(fName.getText().isEmpty()||lName.getText().isEmpty()||eMail.getText().isEmpty()||pNo.getText().isEmpty()||idate.isEmpty()|| pass.isEmpty())
         {
              JOptionPane.showMessageDialog(null,"Please fill all column");
         }
         else{
        u_signup.adduser(fName.getText(),lName.getText(),eMail.getText(),pNo.getText(),idate, pass);
             dispose();
        new     Login_Stu().setVisible(true);
        this.setVisible(false);
                }
                
      
        
        
    }//GEN-LAST:event_signbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB1;
    private javax.swing.JButton backB2;
    private javax.swing.JTextField eMail;
    private javax.swing.JTextField fName;
    private com.toedter.calendar.JDateChooser issue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField pNo;
    private javax.swing.JPasswordField pswdS;
    private javax.swing.JButton signbtn;
    // End of variables declaration//GEN-END:variables
}
